# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chat_service_pb2 as chat__service__pb2


class ChatServiceStub(object):
    """A simple chat service that allows anyone to login and start broadcasting
    message to everyone who currently holds an active connection to the service.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.stream_stream(
                '/chat_service.ChatService/Chat',
                request_serializer=chat__service__pb2.ChatMessage.SerializeToString,
                response_deserializer=chat__service__pb2.ChatMessage.FromString,
                )


class ChatServiceServicer(object):
    """A simple chat service that allows anyone to login and start broadcasting
    message to everyone who currently holds an active connection to the service.
    """

    def Chat(self, request_iterator, context):
        """Broadcasts given message.

        For initial login, client should send an initial message via this RPC to
        open up a bidi-chnanel. All subsequent messages will be broadcasted via
        this channel.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.stream_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=chat__service__pb2.ChatMessage.FromString,
                    response_serializer=chat__service__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat_service.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """A simple chat service that allows anyone to login and start broadcasting
    message to everyone who currently holds an active connection to the service.
    """

    @staticmethod
    def Chat(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/chat_service.ChatService/Chat',
            chat__service__pb2.ChatMessage.SerializeToString,
            chat__service__pb2.ChatMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
